<div  class="mlipskiCars">
    <div><select id="mlipski_cars_brands"></select></div>
    <div><select id="mlipski_cars_models"></select></div>
    <div><button id="mlipskiCars__button">Spradź dostępne części!</button></div>
</div>


<script>
    require(['jquery', 'mage/url'], function($, url){
        jQuery(document).ready( function() {
            let selectedCarModelCurrentState = null;
            let selectedCarBrandAttributeCode = null;

            callApiEndpoint('markę', $('#mlipski_cars_brands'), createUrl('/get-all-brands'), 'brand');
            $('#mlipskiCars__button').click(() => { searchCar(selectedCarBrandAttributeCode, selectedCarModelCurrentState) });

                function callApiEndpoint(optionLabel, selectDomElement, url, actionCode)
                {
                    $.ajax({
                    url: url,
                    type: 'GET',
                    dataType: 'json',
                    success: function(response) {
                        const $select = selectDomElement;
                        const $chooseItemOption = $('<option></option>')
                                .attr('value', "choose_item")
                                .text("-- Wybierz "+optionLabel+" --");
                        $select.append($chooseItemOption);

                        $.each(response, function(index, option) {
                            const $option = $('<option></option>')
                                .attr('value', option.code)
                                .text(option.label);
                            
                            $option.click(() => selectChangeEvent(actionCode, getAdditionalInformation(option, actionCode)));
                            $select.append($option);
                        });
                    },
                    error: function(xhr, status, error) {
                        console.error(error); 
                    }
                });
                }

            function chooseBrand(code) {
                callApiEndpoint('model', $('#mlipski_cars_models'), createUrl('/car/'+code+'/models'), 'model');
                selectedCarBrandAttributeCode = code;
            }

            function createUrl(direction) {
                const baseUrl = "<?= $this->getBaseUrl() ; ?>/rest/all/V1/mlipski";
                return baseUrl + direction;
            }

            function getAdditionalInformation(option, action) {
                switch(action) {
                    case 'brand':
                        return option.code;
                    break;
                    case 'model':
                        return option.id;
                    break;
                }
            }

            function searchCar(attributeCode, attributeId) {
                if (attributeCode === null || attributeId === null) {
                    alert("Wypełnij prawidłowo pola!");
                } else {
                    const createUrl = "<?= $this->getBaseUrl() ; ?>all-cars.html?"+attributeCode+"="+attributeId;
                    window.location.href = createUrl;
                }
            }

            function selectChangeEvent(action, additionalInformation = null) {
                switch(action) {
                    case 'brand':
                        chooseBrand(additionalInformation)
                    break;
                    case 'model':
                        selectedCarModelCurrentState = additionalInformation;
                    break;
                }
            }

        });
    });
</script>